# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-21 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Privatec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srv_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='defaultname', max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('pc_ip', models.CharField(default='0.0.0.0', max_length=200)),
                ('is_lan', models.CharField(default='no', max_length=100)),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('usernums', models.IntegerField(default=10)),
                ('activenums', models.IntegerField(default=0)),
                ('adminUser', models.IntegerField()),
                ('testAdmin', models.IntegerField()),
                ('testAdminpwd', models.CharField(default='admin123', max_length=200)),
                ('nothers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moatprivate.Question'),
        ),
    ]
