# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-21 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moatprivate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatec',
            name='adminUser',
            field=models.IntegerField(default=123456),
        ),
        migrations.AlterField(
            model_name='privatec',
            name='begin_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='privatec',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='privatec',
            name='nothers',
            field=models.TextField(default='no notice'),
        ),
        migrations.AlterField(
            model_name='privatec',
            name='status',
            field=models.CharField(default='not know', max_length=200),
        ),
        migrations.AlterField(
            model_name='privatec',
            name='testAdmin',
            field=models.IntegerField(default=123456),
        ),
    ]
