# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-31 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cmds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Private',
            fields=[
                ('private_id', models.AutoField(primary_key=True, serialize=False)),
                ('srv_id', models.IntegerField(default=0, verbose_name='私有云id')),
                ('name', models.CharField(default='defaultname', max_length=200)),
                ('status', models.CharField(default='not know', max_length=200)),
                ('pc_ip', models.CharField(default='0.0.0.0', max_length=200)),
                ('is_lan', models.CharField(default='no', max_length=100)),
                ('begin_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('usernums', models.IntegerField(default=10)),
                ('activenums', models.IntegerField(default=0)),
                ('adminUser', models.CharField(default='12345678901', max_length=200)),
                ('testAdmin', models.CharField(default='12345678901', max_length=200)),
                ('testAdminpwd', models.CharField(default='admin123', max_length=200)),
                ('nothers', models.TextField()),
            ],
            options={
                'verbose_name': '私有云',
                'verbose_name_plural': '私有云',
            },
        ),
        migrations.CreateModel(
            name='RunResult',
            fields=[
                ('case_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('reqdec', models.TextField(default='')),
                ('resdec', models.TextField(default='')),
                ('ispass', models.IntegerField(default=1, verbose_name='ispass')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='默认名字', max_length=200)),
                ('parent_id', models.IntegerField(default=0, verbose_name='父节点')),
                ('is_parent', models.IntegerField(default=0)),
                ('needlogin', models.IntegerField(default=1)),
                ('srvip', models.CharField(default='200.200.169.212', max_length=20)),
                ('username', models.CharField(default='root', max_length=10)),
                ('rootpwd', models.CharField(default='moatest', max_length=10)),
                ('jsonstr', models.TextField(default='')),
                ('phone', models.CharField(default='', max_length=20)),
                ('phone_pwd', models.CharField(default='12345', max_length=20)),
                ('oprcode', models.CharField(default='', max_length=20)),
                ('servercode', models.CharField(default='', max_length=20)),
                ('verify', models.CharField(default='', max_length=200)),
                ('level', models.IntegerField(default=3)),
                ('case_dec', models.TextField(default='')),
            ],
        ),
    ]
